const initialState = {
  ivents: [],
  curentCoords: [],
  currentWeather: {
    todayWindSpeed: '',
    tomorrowWindSpeed: '',
    afterTomorrowWindSpeed: '',
    inThreeDaysWindSpeed: '',
    todayCloudBaseHeight: '',
    tomorrowCloudBaseHeight: '',
    afterTomorrowCloudBaseHeight: '',
    inThreeDaysCloudBaseHeight: '',
    todayWindDirection: '',
    tomorrowWindDirection: '',
    afterTomorrowWindDirection: '',
    inThreeDaysWindDirection: '',
    todayPrecipitationProbability: '',
    tomorrowPrecipitationProbability: '',
    afterTomorrowPrecipitationProbability: '',
    inThreeDaysPrecipitationProbability: '',
    todayTemp: '',
    tomorrowTemp: '',
    afterTomorrowTemp: '',
    inThreeDaysTemp: '',
    todayThunderstormActivity: '',
    tomorrowThunderstormActivity: '',
    afterTomorrowThunderstormActivity: '',
    inThreeDaysThunderstormActivity: '',
    todayCloudy: '',
    tomorrowCloudy: '',
    afterTomorrowCloudy: '',
    inThreeDaysCloudy: '',
  },
};

export default initialState;
