export const IVENT_INIT = 'IVENT_INIT';
export const IVENT_CREATE = 'IVENT_CREATE';
export const CURRENT_COORDS_GET = 'CURRENT_COORDS_GET';
export const CURRENT_WEATHER_GET = 'CURRENT_WEATHER_GET';
export const IVENT_ADD_PASSENGER = 'IVENT_ADD_PASSENGER';
