
export const IVENT_INIT = 'IVENT_INIT';
export const IVENT_CREATE = 'IVENT_CREATE';
export const CURRENT_COORDS_GET = 'CURRENT_COORDS_GET';
export const CURRENT_WEATHER_GET = 'CURRENT_WEATHER_GET';
export const SELECT_IVENT_GET = 'SELECT_IVENT_GET';
export const IVENT_ADD_PASSENGER = 'IVENT_ADD_PASSENGER';
export const IVENT_DELETE_PASSENGER = 'IVENT_DELETE_PASSENGER';
export const IVENT_ACCEPT_PASSENGER = 'IVENT_ACCEPT_PASSENGER';
export const IVENT_REJECT_PASSENGER = 'IVENT_REJECT_PASSENGER';
export const IVENT_PENDING_PASSENGER = 'IVENT_PENDING_PASSENGER';
export const IVENT_DELETE = "IVENT_DELETE";

